server {
    listen 80;
    server_name localhost; # Calling localhost on browser will reroute to website (if wanna change website name change this and adjust hosts file)

    location / {
        proxy_pass http://127.0.0.1:8080; # Assuming your Node.js app runs on port 8080

        # Used headers to prevent application from having an identity crisis.
        proxy_set_header Host $host; # Tells rust to use the original host header
        proxy_set_header X-Real-IP $remote_addr; # Passes the client's IP address to the backend via nginx
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Allows user to track entire path of the request through the proxy chain
        proxy_set_header X-Forwarded-Proto $scheme; # Tells app whether the original request was HTTP or HTTPS
    }
}